### ISSUE TITLE
Doesn't play well with text-scale-mode

### ISSUE THREAD

**Issue by purcell** [purcell/page-break-lines#3]
`(window-width ...)` always returns the window width in terms of the base font size, whereas the scaled font may display either more or fewer characters in the same width.

**Comment by cpitclaudel** [comment]
Hey Steve,

You may be interested in https://github.com/cpitclaudel/company-coq/commit/4a9793729bf01de6e3d16581da62f67388962cfd . I'm using a variant of page-break-line-mode to display a solid line there and I ran into the same issue.

The trick is to read the face height from the `'default` face (`face-attribute` doesn't take face remapping into account, so you get the right value), and apply that (absolute) height to the `page-break-lines` face:

```elisp
(let ((default-height (face-attribute 'default :height nil 'default)))
  (set-face-attribute 'company-coq-goal-line-face nil :height default-height))
```

Another trick: on some computers the box drawing line is wider than a regular character (so the line wraps) and on others the character isn't displayed (though it's supported). I worked around this by using a plain space as the line-drawing glyph, and adding a strike-through to the line face. On terminals I still use a box-drawing character (since strike-through isn't available), but that's fine because terminals don't have wide characters.

Let me know if this is enough information. Otherwise, I can try to find time to make a PR.

**Comment by purcell** [comment]
Sorry for the very slow reply -- this has been on my to-do list for a few months now!

It's a great tip, and I've incorporated the "default height" part of the fix. Re. using strike-through vs. a line-drawing character, you really shouldn't be choosing one or the other at package load time by inspecting `display-graphic-p`, so your approach will automatically be unreliable. Specifically, that function will return a different value in tty vs. graphic frames, so if you start a TTY or daemon Emacs, and then create a GUI frame (or vice versa) with emacsclient, then you'll be stuck with whichever return value `display-graphic-p` gave in the frame which initially loaded the code.

**Comment by cpitclaudel** [comment]
> so if you start a TTY or daemon Emacs, and then create a GUI frame (or vice versa) with emacsclient, then you'll be stuck with whichever return value display-graphic-p gave in the frame which initially loaded the code.

Oooh that's right. Thanks!
